package com.nutricash.api.health.enums;
public enum HealthRiskFlag { DIABETES_REPORTED, HYPERTENSION_REPORTED, KIDNEY_DISEASE_REPORTED, CARDIOVASCULAR_REPORTED, OTHER_CONDITION_REPORTED, ALLERGY_REPORTED }
