package com.nutricash.api.messenger.controller;

import com.nutricash.api.common.dto.ApiResponse;
import com.nutricash.api.common.dto.ErrorResponse;
import com.nutricash.api.messenger.dto.LinkAccountRequest;
import com.nutricash.api.messenger.service.MessengerAccountService;
import com.nutricash.api.security.SecurityUser;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/messenger/accounts")
@RequiredArgsConstructor
@Slf4j
@Tag(name = "Messenger Account Linking", description = "APIs for linking user profiles to Messenger Chatbot")
@SecurityRequirement(name = "bearerAuth")
public class MessengerAccountController {

    private final MessengerAccountService accountService;

    @PostMapping("/link")
    @Operation(summary = "Link Messenger Account", description = "Links the current user to a Messenger profile using the 6-digit linking code generated by the chatbot.")
    @io.swagger.v3.oas.annotations.responses.ApiResponses(value = {
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "Account linked successfully"),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "400", description = "Validation error (VALIDATION_ERROR)",
                    content = @Content(schema = @Schema(implementation = ErrorResponse.class))),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "401", description = "Unauthorized (UNAUTHORIZED)",
                    content = @Content(schema = @Schema(implementation = ErrorResponse.class))),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "404", description = "Linking code not found or expired (RESOURCE_NOT_FOUND)",
                    content = @Content(schema = @Schema(implementation = ErrorResponse.class)))
    })
    public ApiResponse<Void> linkAccount(
            @AuthenticationPrincipal SecurityUser currentUser,
            @Valid @RequestBody LinkAccountRequest request) {
        log.info("Linking account for user ID: {} with code: {}", currentUser.getId(), request.code());
        accountService.linkAccount(currentUser, request);
        return ApiResponse.success("Messenger account linked successfully", null);
    }

    @DeleteMapping("/unlink")
    @Operation(summary = "Unlink Messenger Account", description = "Unlinks all Messenger profiles associated with the current user.")
    @io.swagger.v3.oas.annotations.responses.ApiResponses(value = {
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "Account unlinked successfully"),
            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "401", description = "Unauthorized (UNAUTHORIZED)",
                    content = @Content(schema = @Schema(implementation = ErrorResponse.class)))
    })
    public ApiResponse<Void> unlinkAccount(
            @AuthenticationPrincipal SecurityUser currentUser) {
        log.info("Unlinking Messenger account for user ID: {}", currentUser.getId());
        accountService.unlinkAccount(currentUser);
        return ApiResponse.success("Messenger account unlinked successfully", null);
    }
}
