package com.nutricash.api.common.enums;
public enum ChatbotActionType { IMAGE_ANALYSIS, TEXT_MEAL, RECEIPT_CONFIRMATION, TRANSFER_CONFIRMATION, BUDGET_UPDATE, MEAL_CLARIFICATION, MEAL_CONFIRMATION, HEALTH_ASSESSMENT }
